pipeline:
  name: ci
  identifier: ci
  projectIdentifier: myapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        build: <+input>
  stages:
    - stage:
        name: build go
        identifier: build_go
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: go build
                  identifier: go_build
                  spec:
                    connectorRef: account.harnessImage
                    image: hargo
                    shell: Bash
                    command: go build
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: ci
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
